apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: 1.21.0
localAPIEndpoint:
  advertiseAddress: "10.10.10.93"
  bindPort: 6443
etcd:
  external:
    endpoints:
    - https://10.10.10.90:2379
    - https://10.10.10.91:2379
    - https://10.10.10.92:2379
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: 10.30.0.0/24
apiServer:
  certSANs:
  - "10.10.10.93"
  extraArgs:
    apiserver-count: "3"
