apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: demo-world
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: demo-world